services:
  oracle:
    image: gvenzl/oracle-free:latest
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ./scripts:/container-entrypoint-initdb.d
    environment:
      ORACLE_PASSWORD: ROOT