CONNECT SYSTEM/ROOT@FREEPDB1;

CREATE USER "PRIMARY" IDENTIFIED BY "PRIMARY" DEFAULT TABLESPACE USERS PROFILE DEFAULT QUOTA UNLIMITED ON USERS;
CREATE USER "SECONDARY" IDENTIFIED BY "SECONDARY"  DEFAULT TABLESPACE USERS PROFILE DEFAULT QUOTA UNLIMITED ON USERS;

GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE VIEW TO "PRIMARY";
GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE VIEW TO "SECONDARY";

COMMIT;
