spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/freepdb1
    username: PRIMARY
    password: PRIMARY
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
  jpa:
    database: oracle
    open-in-view: false
    hibernate:
      ddl-auto: validate