ALTER SESSION SET CONTAINER=FREEPDB1;

CREATE USER "SECONDARY-A" IDENTIFIED BY "SECONDARY-A";
CREATE USER "SECONDARY-B" IDENTIFIED BY "SECONDARY-B";

GRANT CONNECT, RESOURCE TO "SECONDARY-A";
GRANT CONNECT, RESOURCE TO "SECONDARY-B";

ALTER USER "SECONDARY-A" QUOTA UNLIMITED ON USERS;
ALTER USER "SECONDARY-B" QUOTA UNLIMITED ON USERS;
